import {
  approveOpportunityAction,
  rejectOpportunityAction,
  updateOpportunityAction,
} from "@/app/actions/content-opportunities";
import { generateBriefAction } from "@/app/actions/content-briefs";
import { ActionForm, SubmitButton } from "@/components/forms/action-form";
import {
  Badge,
  Card,
  CardHeader,
  Chips,
  Field,
  Input,
  KeyValue,
  OriginBadge,
  PageHeader,
  Select,
  Textarea,
} from "@/components/ui";
import { hasCapability, requireBrandAccess } from "@/lib/auth/context";
import { getCsrfToken } from "@/lib/auth/session";
import { getOpportunityDetail } from "@/services/content-opportunities";
import { RECOMMENDATION_TYPES } from "@/prompts/schemas";

export const dynamic = "force-dynamic";

export default async function OpportunityDetailPage({
  params,
}: {
  params: Promise<{ brandId: string; opportunityId: string }>;
}) {
  const { brandId, opportunityId } = await params;
  const ctx = await requireBrandAccess(brandId);

  const [opportunity, csrfToken] = await Promise.all([
    getOpportunityDetail(ctx, opportunityId),
    getCsrfToken(),
  ]);

  const canApprove = hasCapability(ctx, "content:approve");
  const canEdit = hasCapability(ctx, "content:generate");
  const mutable =
    opportunity.reviewStatus !== "approved" && opportunity.reviewStatus !== "rejected";
  const exportBase = `/brands/${brandId}/opportunities/export?id=${opportunityId}&format`;

  return (
    <>
      <PageHeader
        title={opportunity.title}
        breadcrumb={`${ctx.brandName} / Content opportunities / ${opportunity.title}`}
        actions={
          <span className="flex items-center gap-2">
            <OriginBadge origin={opportunity.dataOrigin} />
            <Badge
              tone={
                opportunity.reviewStatus === "approved"
                  ? "success"
                  : opportunity.reviewStatus === "rejected"
                    ? "danger"
                    : "neutral"
              }
            >
              {opportunity.reviewStatus.replace(/_/g, " ")}
            </Badge>
          </span>
        }
      />

      <Card className="mb-4">
        <CardHeader
          title="Recommendation"
          description={opportunity.recommendationRationale}
          actions={
            <span className="flex gap-2 text-xs">
              <a className="text-accent hover:underline" href={`${exportBase}=json`}>
                Export JSON
              </a>
              <a className="text-accent hover:underline" href={`${exportBase}=csv`}>
                CSV
              </a>
              <a className="text-accent hover:underline" href={`${exportBase}=md`}>
                Markdown
              </a>
            </span>
          }
        />
        <div className="space-y-3 px-4 py-3">
          <KeyValue
            items={[
              { label: "Gap type", value: <Badge tone="accent">{opportunity.gapType}</Badge> },
              { label: "Recommendation", value: opportunity.recommendation.replace(/_/g, " ") },
              { label: "Priority", value: opportunity.priority.toUpperCase() },
              { label: "Estimated effort", value: opportunity.estimatedEffort },
              { label: "Persona", value: opportunity.personaName ?? "—" },
              { label: "Existing page", value: opportunity.existingPageUrl ?? "None" },
              {
                label: "Competitors present",
                value: <Chips values={opportunity.competitors} />,
              },
              {
                label: "Citation sources",
                value: <Chips values={opportunity.citationSources} />,
              },
              {
                label: "Missing answer elements",
                value: <Chips values={opportunity.missingAnswerElements} tone="accent" />,
              },
              { label: "Evidence ids", value: opportunity.evidenceIds.join(", ") || "none" },
              {
                label: "Profound prompt ids",
                value: opportunity.relevantProfoundPromptIds.join(", ") || "none",
              },
              { label: "Run ids", value: opportunity.relevantRunIds.join(", ") || "none" },
              { label: "Validation method", value: opportunity.validationMethod },
              {
                label: "Generated by",
                value: opportunity.generatedByName ?? opportunity.modelId ?? "—",
              },
            ]}
          />
        </div>
      </Card>

      <Card className="mb-4">
        <CardHeader title="Problem statement" />
        <p className="px-4 py-3 text-sm text-ink">{opportunity.problemStatement}</p>
      </Card>

      <Card className="mb-4">
        <CardHeader title="Performance gap" />
        <p className="px-4 py-3 text-sm text-ink">{opportunity.performanceGap}</p>
      </Card>

      {mutable && (canApprove || canEdit) ? (
        <Card className="mb-4">
          <CardHeader title="Review" />
          <div className="flex flex-wrap gap-4 px-4 py-3">
            {canApprove ? (
              <ActionForm
                action={approveOpportunityAction}
                csrfToken={csrfToken}
                hidden={{ brandId, opportunityId }}
                className="space-y-0"
              >
                <SubmitButton label="Approve" />
              </ActionForm>
            ) : null}
            {canApprove ? (
              <ActionForm
                action={rejectOpportunityAction}
                csrfToken={csrfToken}
                hidden={{ brandId, opportunityId }}
              >
                <Field label="Rejection reason">
                  <Textarea name="reason" rows={2} required />
                </Field>
                <SubmitButton label="Reject" variant="danger" />
              </ActionForm>
            ) : null}
          </div>
        </Card>
      ) : null}

      {mutable && canEdit ? (
        <Card className="mb-4">
          <CardHeader title="Edit" description="Editable while pending review." />
          <ActionForm
            action={updateOpportunityAction}
            csrfToken={csrfToken}
            hidden={{ brandId, opportunityId }}
          >
            <Field label="Title">
              <Input name="title" defaultValue={opportunity.title} required />
            </Field>
            <Field label="Problem statement">
              <Textarea
                name="problemStatement"
                rows={3}
                defaultValue={opportunity.problemStatement}
                required
              />
            </Field>
            <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
              <Field label="Recommendation">
                <Select name="recommendation" defaultValue={opportunity.recommendation}>
                  {RECOMMENDATION_TYPES.map((value) => (
                    <option key={value} value={value}>
                      {value.replace(/_/g, " ")}
                    </option>
                  ))}
                </Select>
              </Field>
              <Field label="Priority">
                <Select name="priority" defaultValue={opportunity.priority}>
                  <option value="p1">P1</option>
                  <option value="p2">P2</option>
                  <option value="p3">P3</option>
                </Select>
              </Field>
              <Field label="Estimated effort">
                <Select name="estimatedEffort" defaultValue={opportunity.estimatedEffort}>
                  <option value="small">Small</option>
                  <option value="medium">Medium</option>
                  <option value="large">Large</option>
                </Select>
              </Field>
            </div>
            <Field label="Validation method">
              <Textarea
                name="validationMethod"
                rows={2}
                defaultValue={opportunity.validationMethod}
                required
              />
            </Field>
            <SubmitButton label="Save changes" variant="secondary" />
          </ActionForm>
        </Card>
      ) : null}

      {opportunity.reviewStatus === "approved" ? (
        <Card>
          <CardHeader
            title="Generate SEO brief"
            description="Produces all 27 required brief sections, traceable to this opportunity's evidence and Profound prompts."
          />
          <div className="px-4 py-3">
            <ActionForm
              action={generateBriefAction}
              csrfToken={csrfToken}
              hidden={{ brandId, opportunityId }}
            >
              <SubmitButton label="Generate brief" pendingLabel="Queuing…" />
            </ActionForm>
          </div>
        </Card>
      ) : null}
    </>
  );
}
